# Generated by Django 6.0.7 on 2026-07-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IT', 'Information Technology')], max_length=10)),
                ('year_of_admission', models.IntegerField()),
                ('semester', models.IntegerField(default=1)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
    ]
